# Generated by Django 5.1.6 on 2026-08-12 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sessao_app_id", models.CharField(max_length=80, unique=True)),
                ("operador_nome", models.CharField(max_length=160)),
                ("operador_matricula", models.CharField(max_length=60)),
                ("data_inicio", models.DateTimeField()),
                ("data_fim_real", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="recebida", max_length=40)),
                ("versao_cadastro", models.CharField(blank=True, max_length=80)),
                ("aparelho", models.CharField(blank=True, max_length=120)),
                ("total_itens", models.PositiveIntegerField(default=0)),
                (
                    "total_contado",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "total_recebido",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("payload_original", models.JSONField(default=dict)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ItemContagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_codigo", models.CharField(max_length=80)),
                ("fornecedor", models.CharField(blank=True, max_length=120)),
                ("material_descricao", models.CharField(blank=True, max_length=240)),
                (
                    "estoque_anterior",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "estoque_contado",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "recebimento_total",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "soma_nf",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("status", models.CharField(max_length=40)),
                ("justificativa", models.TextField(blank=True)),
                ("observacao", models.TextField(blank=True)),
                ("foto_path", models.CharField(blank=True, max_length=500)),
                ("timestamp_item", models.DateTimeField(blank=True, null=True)),
                ("payload_original", models.JSONField(default=dict)),
                (
                    "contagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="contagens.contagem",
                    ),
                ),
            ],
            options={
                "ordering": ["fornecedor", "material_descricao", "material_codigo"],
                "unique_together": {("contagem", "material_codigo")},
            },
        ),
    ]
