# Generated by Django 5.1.6 on 2026-08-12 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contagens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaRecebimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=120)),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("data_recebimento", models.DateTimeField(blank=True, null=True)),
                ("foto_path", models.CharField(blank=True, max_length=500)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="contagens.itemcontagem",
                    ),
                ),
            ],
            options={
                "ordering": ["numero"],
            },
        ),
    ]
